"""Initial migration

Revision ID: 5891b11ef339
Revises: 20d90dd2b1a2
Create Date: 2025-01-12 19:18:46.426172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5891b11ef339'
down_revision = '20d90dd2b1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siparis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.DateTime(), nullable=True),
    sa.Column('toplam_fiyat', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siparis')
    # ### end Alembic commands ###
