"""Initial migration

Revision ID: 90273345b125
Revises: 5891b11ef339
Create Date: 2025-01-12 19:20:31.359513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90273345b125'
down_revision = '5891b11ef339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siparis_urun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siparis_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('adet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['siparis_id'], ['siparis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siparis_urun')
    # ### end Alembic commands ###
