"""Initial migration

Revision ID: b0f3a8f89b10
Revises: bf867f9d201d
Create Date: 2025-01-11 23:19:39.417690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f3a8f89b10'
down_revision = 'bf867f9d201d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('yas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cinsiyet', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('miktar', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('miktar')
        batch_op.drop_column('cinsiyet')
        batch_op.drop_column('yas')
        batch_op.drop_column('kategori')

    # ### end Alembic commands ###
