"""siparis durum ve kargo takip

Revision ID: b36880028471
Revises: 90273345b125
Create Date: 2025-05-15 23:01:04.147009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36880028471'
down_revision = '90273345b125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siparis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durum', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kargo_takip_no', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('iptal_edildi', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siparis', schema=None) as batch_op:
        batch_op.drop_column('iptal_edildi')
        batch_op.drop_column('kargo_takip_no')
        batch_op.drop_column('durum')

    # ### end Alembic commands ###
