"""Initial migration

Revision ID: bf867f9d201d
Revises: cced9a07d1f2
Create Date: 2025-01-11 02:36:54.821466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf867f9d201d'
down_revision = 'cced9a07d1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urun_etiket', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['urun_etiket'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('urun_etiket')

    # ### end Alembic commands ###
