"""Initial migration

Revision ID: fcbda2e7762b
Revises: b0f3a8f89b10
Create Date: 2025-01-11 23:34:37.556735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbda2e7762b'
down_revision = 'b0f3a8f89b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renk', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('renk')

    # ### end Alembic commands ###
